/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package horario;

import java.awt.Toolkit;
import javax.swing.DefaultListModel;

/**
 *
 * @author soeur
 */
public class MenuRels extends javax.swing.JFrame {
    private DefaultListModel listaM;
    private DefaultListModel listaAct;
    private DefaultListModel listaRel;
    int [][] matAdy;
 //   String [] mats;
    
    /**
     * Creates new form MenuRels
     */
    public MenuRels() {
        initComponents();
    }
    
    public MenuRels(DefaultListModel l) {
        initComponents();
        listaM = l;
        matAdy = new int [l.size()][l.size()];
//        mats = new String [l.size()];
//        añadeMaterias();
        listaAct = new DefaultListModel();
        listaRel = new DefaultListModel();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("horario.png")));
        jListaMat.setModel(listaM);
        jListaRel.setVisible(false);
        jRelaciones.setVisible(false);
        labelAdver.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jListaMat = new javax.swing.JList<>();
        btnAgregaM = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListaRel = new javax.swing.JList<>();
        btnQuitaM = new javax.swing.JButton();
        btnAgregaRel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jRelaciones = new javax.swing.JList<>();
        btnQuitaRel = new javax.swing.JButton();
        btnQuitaTodas = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnCont = new javax.swing.JButton();
        labelAdver = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jListaMat.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListaMatValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jListaMat);

        btnAgregaM.setText("Agregar Materia");
        btnAgregaM.setEnabled(false);
        btnAgregaM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregaMActionPerformed(evt);
            }
        });

        jListaRel.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListaRelValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jListaRel);

        btnQuitaM.setText("Quitar Materia");
        btnQuitaM.setEnabled(false);
        btnQuitaM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitaMActionPerformed(evt);
            }
        });

        btnAgregaRel.setText("Agregar Relación");
        btnAgregaRel.setEnabled(false);
        btnAgregaRel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregaRelActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel1.setText("Agregue las materias que están relacionadas entre sí.");

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel2.setText("Relaciones enlistadas");

        jScrollPane3.setViewportView(jRelaciones);

        btnQuitaRel.setText("Quitar Relación");
        btnQuitaRel.setEnabled(false);
        btnQuitaRel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitaRelActionPerformed(evt);
            }
        });

        btnQuitaTodas.setText("Quitar todas");
        btnQuitaTodas.setEnabled(false);
        btnQuitaTodas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitaTodasActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel3.setText("Materias");

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel4.setText("Relación");

        btnCont.setText("Continuar");
        btnCont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContActionPerformed(evt);
            }
        });

        labelAdver.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        labelAdver.setText("Las relaciones deben ser entre 2 o más materias");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCont))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(28, 28, 28)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnQuitaRel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnQuitaTodas, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jLabel2)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnAgregaRel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnQuitaM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnAgregaM, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jLabel3))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(labelAdver))
                    .addComponent(jLabel1))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelAdver)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btnAgregaM)
                        .addGap(38, 38, 38)
                        .addComponent(btnQuitaM)
                        .addGap(42, 42, 42)
                        .addComponent(btnAgregaRel)))
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnQuitaRel)
                        .addGap(31, 31, 31)
                        .addComponent(btnQuitaTodas)))
                .addGap(4, 4, 4)
                .addComponent(btnCont)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(603, 573));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jListaMatValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListaMatValueChanged
        btnAgregaM.setEnabled(true);
        
    }//GEN-LAST:event_jListaMatValueChanged

    private void btnAgregaMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregaMActionPerformed
        if(listaAct.contains(listaM.getElementAt(jListaMat.getSelectedIndex()))){
            labelAdver.setText("La materia ya está dentro de la relación");
            labelAdver.setVisible(true);
        }else{
            labelAdver.setVisible(false);
            jListaRel.setVisible(true);
            listaAct.addElement(listaM.getElementAt(jListaMat.getSelectedIndex()));
            jListaRel.setModel(listaAct);
            btnAgregaRel.setEnabled(true);
            btnAgregaM.setEnabled(false);
        }        
    }//GEN-LAST:event_btnAgregaMActionPerformed

    private void jListaRelValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListaRelValueChanged
        btnQuitaM.setEnabled(true);
    }//GEN-LAST:event_jListaRelValueChanged

    private void btnQuitaMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitaMActionPerformed
        listaAct.remove(jListaRel.getSelectedIndex());
        btnAgregaM.setEnabled(false);
        btnQuitaM.setEnabled(false);
    }//GEN-LAST:event_btnQuitaMActionPerformed

//    public void añadeMaterias(){
//        for (int i = 0; i < listaM.size(); i++) {
//            mats[i] = listaM.elementAt(i).toString();
//        }
//        imprimeMats();
//    }
    
    public void imprimeMats(){
        for(int i = 0; i < listaM.size(); i++){
            System.out.print(listaM.getElementAt(i).toString()+" ");
        }
        System.out.println();
    }
    
    public void imprimeMatRels(){
        for(int i = 0; i < listaM.size(); i++){
            for(int j = 0; j < listaM.size(); j++){
                System.out.print(matAdy[i][j]+" ");
            }
            System.out.println();
        }
    }
    
    
    public void insertaRel(DefaultListModel l, int tam){
        for(int i = 0; i < tam; i ++){
            int sig = listaM.indexOf(listaAct.elementAt(i));
            for(int j = 0; j < tam; j++){
                if(i != j){
                    int nuevo = listaM.indexOf(listaAct.elementAt(j));                    
                    if(matAdy [sig][nuevo] == 0){
                        matAdy [sig][sig]++;
                    }
                    matAdy [sig][nuevo] = 1;
                    
                }
            }
        }
    }

    private void btnAgregaRelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregaRelActionPerformed
        String rel = "";
        int tam = listaAct.size();
        if(tam < 2){
            labelAdver.setText("Las relaciones deben de ser entre 2 materias o más.");
            labelAdver.setVisible(true);
        }else{
            insertaRel(listaAct, tam);
            imprimeMatRels();
            System.out.println();
            for(int i = 0; i < tam; i ++){
                rel+=listaAct.getElementAt(i);
                if(i < tam - 1){
                    rel+=" - ";
                }
            }
            listaRel.addElement(rel);
            listaAct.clear();
            jRelaciones.setModel(listaRel);
            btnQuitaTodas.setEnabled(true);
            btnAgregaM.setEnabled(false);
            btnQuitaM.setEnabled(false);
            btnAgregaRel.setEnabled(false);
            jListaRel.setVisible(false);
            jRelaciones.setVisible(true);
        }
    }//GEN-LAST:event_btnAgregaRelActionPerformed

    private void btnQuitaTodasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitaTodasActionPerformed
        listaAct.clear();
        listaRel.clear();
        jRelaciones.setVisible(false);
        btnQuitaTodas.setEnabled(false);
    }//GEN-LAST:event_btnQuitaTodasActionPerformed

    private void btnQuitaRelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitaRelActionPerformed
        listaRel.remove(jRelaciones.getSelectedIndex());
        btnQuitaRel.setEnabled(false);
        if(listaRel.isEmpty()){
            jRelaciones.setVisible(false);
        }
    }//GEN-LAST:event_btnQuitaRelActionPerformed

    private void btnContActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContActionPerformed
        Restricciones r = new Restricciones(listaM, matAdy, listaRel);
        r.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnContActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuRels.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuRels.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuRels.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuRels.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuRels().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregaM;
    private javax.swing.JButton btnAgregaRel;
    private javax.swing.JButton btnCont;
    private javax.swing.JButton btnQuitaM;
    private javax.swing.JButton btnQuitaRel;
    private javax.swing.JButton btnQuitaTodas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<String> jListaMat;
    private javax.swing.JList<String> jListaRel;
    private javax.swing.JList<String> jRelaciones;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelAdver;
    // End of variables declaration//GEN-END:variables
}
