/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package horario;

import java.awt.Toolkit;
import javax.swing.DefaultListModel;

/**
 *
 * @author soeur
 */
public class Menu extends javax.swing.JFrame {
    //no necesitamos aquí arreglo de materias, este se va a crear después
    private int tot = 1;
    private int cont = 1;
    
    private DefaultListModel lista = new DefaultListModel();

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        jListo.setVisible(false);
        jListaMaterias.setVisible(false);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("horario.png")));
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nomMat = new javax.swing.JTextField();
        btIngresa = new javax.swing.JButton();
        btCont = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jListo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jNums = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListaMaterias = new javax.swing.JList<>();
        btnEliminaMat = new javax.swing.JButton();
        btnEliminaTodas = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ingrese el nombre de las materias para armar el horario.");

        nomMat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nomMatMouseClicked(evt);
            }
        });

        btIngresa.setText("Ingresar");
        btIngresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIngresaActionPerformed(evt);
            }
        });

        btCont.setText("Continuar");
        btCont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btContActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel2.setText("Nombre de materia:");

        jListo.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jListo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jListo.setText("Número de materias excedido");

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel3.setText("Ingrese cantidad de materias. ");

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel4.setText("Número de materias:");

        jNums.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27" }));
        jNums.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jNumsItemStateChanged(evt);
            }
        });

        jListaMaterias.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListaMaterias.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListaMateriasValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jListaMaterias);

        btnEliminaMat.setText("Eliminar materia");
        btnEliminaMat.setEnabled(false);
        btnEliminaMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminaMatActionPerformed(evt);
            }
        });

        btnEliminaTodas.setText("Eliminar todas");
        btnEliminaTodas.setEnabled(false);
        btnEliminaTodas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminaTodasActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel5.setText("Materias enlistadas:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(47, 47, 47)
                                .addComponent(jNums, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(28, 28, 28)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnEliminaMat)
                                        .addComponent(btnEliminaTodas)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btCont))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jListo)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(341, 341, 341)
                                    .addComponent(btIngresa))
                                .addComponent(nomMat, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2)))))
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jNums, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btIngresa))
                .addGap(18, 18, 18)
                .addComponent(jListo)
                .addGap(14, 14, 14)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(34, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEliminaMat)
                        .addGap(38, 38, 38)
                        .addComponent(btnEliminaTodas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btCont)
                        .addGap(17, 17, 17))))
        );

        setSize(new java.awt.Dimension(519, 507));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btIngresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIngresaActionPerformed
        if(cont <= tot){
            String nom = nomMat.getText();
            lista.addElement(nom);
            nomMat.setText("");
            jListo.setText("Materia agregada");
            jListo.setVisible(true);
            cont ++;
            
        }else{
            jListo.setVisible(true);
            jListo.setText("Número de materias excedido");
        }
        jListaMaterias.setModel(lista);
        jListaMaterias.setVisible(true);
        btnEliminaTodas.setEnabled(true);
        btnEliminaMat.setEnabled(false);
    }//GEN-LAST:event_btIngresaActionPerformed

    private void jNumsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jNumsItemStateChanged
        tot = Integer.parseInt(jNums.getSelectedItem().toString());
        jListo.setVisible(false);
    }//GEN-LAST:event_jNumsItemStateChanged

    private void jListaMateriasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListaMateriasValueChanged
        btnEliminaMat.setEnabled(true);
    }//GEN-LAST:event_jListaMateriasValueChanged

    private void btnEliminaMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminaMatActionPerformed
        int index = jListaMaterias.getSelectedIndex();
        lista.remove(index);
        cont--;
        jListo.setVisible(true);
        jListo.setText("Materia eliminada");
        btnEliminaMat.setEnabled(false);
        
    }//GEN-LAST:event_btnEliminaMatActionPerformed

    private void btnEliminaTodasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminaTodasActionPerformed
        lista.clear();
        cont = 1;
        jListo.setVisible(false);
        jListaMaterias.setVisible(false);
        btnEliminaTodas.setEnabled(false);
        btnEliminaMat.setEnabled(false);
    }//GEN-LAST:event_btnEliminaTodasActionPerformed

    private void btContActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btContActionPerformed
        if(cont - 1 < tot){
            jListo.setText("Faltan materias por agregar");
        }else{
            
            MenuRels siguiente = new MenuRels(lista);
            siguiente.setVisible(true);
            this.dispose();
                       
        }        
    }//GEN-LAST:event_btContActionPerformed

    private void nomMatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nomMatMouseClicked
        jListo.setVisible(false);
    }//GEN-LAST:event_nomMatMouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCont;
    private javax.swing.JButton btIngresa;
    private javax.swing.JButton btnEliminaMat;
    private javax.swing.JButton btnEliminaTodas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList<String> jListaMaterias;
    private javax.swing.JLabel jListo;
    private javax.swing.JComboBox<String> jNums;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nomMat;
    // End of variables declaration//GEN-END:variables

    
}
